---
- name: Checking essentials
  apt: name={{ item }} state=present
  with_items:
  - build-essential
  - curl
  - git
  - vim

- name: roll out new code
  action: git repo=git@github.com:ipedrazas/dotmarks.git dest=/home/{{user}}/releases version=HEAD branch=release
