---
- name: Checking essentials
  apt: name={{ item }} state=present
  with_items:
  - build-essential
  - curl
  - git

- name: roll out new code
  action: git repo=https://github.com/ipedrazas/dotmarks.git dest=/home/{{user}}/releases version=HEAD
