---
- name: Checking essentials
  apt: name={{ item }} state=present
  with_items:
  - python-software-properties
  - python-pycurl
  - build-essential
  - curl
  - git 
  - vim 
  - python-pip 
  - python-dev
