---

- name: Assures {{virtualenv_dir}}/etc dir exists
  file: path={{virtualenv_dir}}/etc state=directory
  sudo_user: vagrant

- name: create folder for gunicorn.conf.py
  template: src=gunicorn.conf.py.j2
            dest={{virtualenv_dir}}/etc/gunicorn.conf.py
  sudo_user: vagrant


- name: write gunicorn init script
  template: src=postworker.conf.j2
            dest=/etc/supervisor/conf.d/postworker.conf


