---
- name: Checking essentials
  apt: name={{ item }} state=present
  with_items:
  - libffi-dev
  - supervisor

- name: install virtualenv
  pip: name={{ item }} state=present
  with_items:
  - virtualenv
  - bcrypt
  - gunicorn

- file: path=/home/vagrant/Envs state=directory owner=vagrant
