

---

- name: Get the current date.
  action: shell date '+%s'
  register: CURRENT_DATE

- name: roll out new code
  action: git repo=https://github.com/ipedrazas/dotmarks.git dest=/home/{{user}}/releases/{{ CURRENT_DATE.stdout }} version=HEAD
